### ISSUE TITLE
Leaderboard doesnt work ://

### ISSUE THREAD

**Issue by kinggenericc** [birbified/discord-mongo-currency#2]

**Comment by ConnorDoesDev** [comment]
what's the error

**Comment by rapsavage1** [comment]
I've gotten 
(node:8152) UnhandledPromiseRejectionWarning: ReferenceError: u is not defined

and 

 (node:14920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of undefined
 
 Leaderboard worked when there was only one user in the database but once I added a second one it gave me those two errors, I fixed the "u is not defined" by changing it to an "i", but the tag error still persists. I was able to get my bot to send the embed if I removed "tag" from the code, but it would only show my discord username and the second account would show up as "Nobody". I still haven't figured out to get around it.

**Comment by ConnorDoesDev** [comment]
look at my pr

**Comment by BumbaDavid** [comment]
Got an error when trying to use the leaderboard command :
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of undefined. If i remove the "tag" from the code, i get all 10 members on the leaderboard, but their name is "Nobody"
