### ISSUE TITLE
Deposit not a function

### ISSUE THREAD

**Issue by ItsDiino** [birbified/discord-mongo-currency#8]
I got this error when trying to do deposit command:
(node:607) UnhandledPromiseRejectionWarning: TypeError: mongoCurrency.deposit is not a function

**Comment by asolden22** [comment]
In the same "Documentation" it says that it was not finished completely, "Deposits coins from the users wallet. **Still not finished completely.**"

**Comment by Rahuletto** [comment]
When ? Last updated is 1 year ago ?

**Comment by asolden22** [comment]
There are many copies and pastes of this package, it is as if they were duplicated, for me it was a joke but hey, I am doing the same but more improved, if you want you can see it in my github profile.

**Comment by ItsDiino** [comment]
> When ? Last updated is 1 year ago !

I would recommend using discord-mongo-currency-fork cus they have deposit and withdraw.

**Comment by Rahuletto** [comment]
Thx
